### PR TITLE
Ported to Gtk3 and some miscellaneous fixes

### PR DESCRIPTION
**Pull request by yell0wfl4sh**
- Ported to Gtk3
- Updated activity.info
- Fixed some errors displayed in terminal

@quozl  please review!

### CODE REVIEW

**Comment by rhl-bthr** [comment]
A port already existed in gtk3 branch. I have merged the same.
Kindly resolve the conflicts in your fork

**Comment by yell0wfl4sh** [comment]
I still don't understand why was a three year old branch given preference to a latest PR. My code somewhat contains some additional changes that it doesn't. I disagree with the fact that you merged it without even concerning someone's existing pull request.

**Comment by rhl-bthr** [comment]
@yashagrawal3 
 - I don't believe time of writing the code is relevant here
 - I did concern your pull request, the idea is to incorporate the changes of both.
   Hence, I requested you to resolve conflicts so that your new changes can also be accomodated.

@quozl, kindly review

**Comment by yell0wfl4sh** [comment]
Time of commit is relevant because of the practice that might have changed in due course of time. And I am talking here about concerning me before merging the branch. I better way would have been acknowleding me about the port, since I have already spent considerable amount of time studying its code, so I would have been better judge of what to merge. I request you to wait for census before making decision in future if others are also involved.

**Comment by rhl-bthr** [comment]
Sure,
Although I did a test and review before merge, if you still feel there are some changes to be incorporated, kindly resolve the conflicts and add them

**Comment by quozl** [comment]
Heh.  We've hit this so often; hidden branch; we need a checklist for activity maintainers.  It does cause wasted effort, but the blame is distributed; @i5o and @walterbender for not merging their branch, everyone else and @quozl for ignoring the branch, @yashagrawal3 for not checking for the branch.

Agree that seeking consensus is an option; but that adds delay.  Has to be a reason for delay.  @yashagrawal3's commit still exists, so it can still be merged, and any of us can do that, but the best person would be whoever has most recently edited the code.  If @yashagrawal3 is not able to do that, then let's merge the commit into a branch gtk3-alternate and create a new issue to track it.  I'd like to make sure the PyGObject version warnings are fixed; they aren't in the master branch in a quick check.

I don't think we can make any specific procedural rule.

**Comment by yell0wfl4sh** [comment]
@quozl there are too many conflicts for my liking, I'll prefer to work on a new branch and incorporate changes I made here to the master branch. No worries about my old commits, it was my fault not checking for the branch, will take care of this in future.

**Comment by quozl** [comment]
Resolving the conflicts by hand is a useful skill.

Every situation is different, but this situation benefited from;

* `git remote add` of your fork,
* `git fetch` of your fork,
* `git diff -R` so that the changes are expressed as against your branch,
* `git diff -w` to overcome the line endings change which caused most conflicts,

In one window I had `git diff -R -w yg/master`, in the other the source files.

See https://github.com/sugarlabs/triples/commit/d92c9c5e4bc89b6c0f17f6d004ab80d73fdceea4 for my resolution of the conflicts.

Note that `gi.require_version` for each module is only needed in the first source file that runs.

**Comment by yell0wfl4sh** [comment]
@quozl 
Thankyou for such a detailed explaination, it's always great to learn new things :). I tried these things out on my machine and it did make the task of resolving conflicts easier.
I'll be merging ```prl-cp``` branch to master, Thanks! 

> ```gi.require_version``` for each module is only needed in the first source file that runs.

Noted.

**Pull request closed without merging**
